import React, { useState } from 'react';
import {
  AlertOctagon,
  Radio,
  BellRing,
  Filter,
  CheckCircle2,
  Send,
  Users,
  Clock,
  ShieldAlert,
  ChevronRight,
  ExternalLink,
  Volume2
} from 'lucide-react';
import { useDisaster } from '../context/DisasterContext';
import { RiskBadge } from '../components/common/RiskBadge';
import { Modal } from '../components/common/Modal';

export function AlertsPage() {
  const { alerts, acknowledgeAlert, setActiveTab, setSelectedLocationId } = useDisaster();

  const [severityFilter, setSeverityFilter] = useState('All');
  const [statusTab, setStatusTab] = useState('Active'); // 'Active' | 'All' | 'Resolved'
  const [selectedAlert, setSelectedAlert] = useState(null);
  const [broadcastSuccess, setBroadcastSuccess] = useState('');

  // Filter alerts
  const filteredAlerts = alerts.filter((alert) => {
    const matchesSeverity =
      severityFilter === 'All' || alert.severity.toLowerCase() === severityFilter.toLowerCase();
    const matchesStatus =
      statusTab === 'All' ||
      (statusTab === 'Active' && alert.status !== 'Resolved') ||
      (statusTab === 'Resolved' && alert.status === 'Resolved');

    return matchesSeverity && matchesStatus;
  });

  const handleBroadcast = (alert) => {
    setBroadcastSuccess(`Emergency CAP Alert & Cell Broadcast triggered for ${alert.location}!`);
    setTimeout(() => setBroadcastSuccess(''), 4000);
  };

  const handleInspectLocation = (sectorId) => {
    setSelectedLocationId(sectorId);
    setActiveTab('map');
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-4 border-b border-slate-800">
        <div>
          <h1 className="text-xl sm:text-2xl font-extrabold text-white flex items-center gap-2.5">
            <AlertOctagon className="text-rose-500 animate-pulse" size={24} />
            Public Early Warning & Emergency Advisories
          </h1>
          <p className="text-xs sm:text-sm text-slate-400 mt-1">
            Official disaster bulletins generated by real-time pore pressure alarms and confirmed ground fissures.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <div className="px-3 py-1.5 rounded-xl bg-rose-950/60 border border-rose-800 text-rose-400 text-xs font-mono font-bold flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-rose-500 animate-ping"></span>
            <span>CAP / NDMA BROADCAST ONLINE</span>
          </div>
        </div>
      </div>

      {broadcastSuccess && (
        <div className="p-4 rounded-xl bg-gradient-to-r from-emerald-950 to-command-900 border border-emerald-700 text-emerald-300 text-xs sm:text-sm flex items-center gap-3 shadow-lg">
          <CheckCircle2 size={20} className="text-emerald-400 shrink-0" />
          <span className="font-semibold">{broadcastSuccess}</span>
        </div>
      )}

      {/* Control Filters Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 bg-command-900 border border-slate-800 rounded-xl p-3 shadow-lg">
        {/* Status Tabs */}
        <div className="flex items-center gap-1 bg-command-950 p-1 rounded-lg border border-slate-800">
          {['Active', 'Resolved', 'All'].map((tab) => (
            <button
              key={tab}
              onClick={() => setStatusTab(tab)}
              className={`px-3 py-1.5 rounded-md text-xs font-semibold transition-all ${
                statusTab === tab
                  ? 'bg-slate-800 text-white shadow'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              {tab === 'Active' ? 'Active Warnings' : tab}
            </button>
          ))}
        </div>

        {/* Severity Filters */}
        <div className="flex flex-wrap items-center gap-1.5">
          <span className="text-xs text-slate-400 font-semibold flex items-center gap-1 mr-1">
            <Filter size={13} /> Severity:
          </span>
          {['All', 'Critical', 'High', 'Moderate', 'Low'].map((sev) => (
            <button
              key={sev}
              onClick={() => setSeverityFilter(sev)}
              className={`px-2.5 py-1 rounded-lg text-xs font-semibold border transition-all ${
                severityFilter === sev
                  ? 'bg-slate-100 text-slate-900 border-white font-bold'
                  : 'bg-command-950 text-slate-400 border-slate-800 hover:text-slate-200'
              }`}
            >
              {sev}
            </button>
          ))}
        </div>
      </div>

      {/* Alerts Cards Stream */}
      <div className="space-y-4">
        {filteredAlerts.length === 0 ? (
          <div className="text-center py-12 bg-command-900/60 rounded-2xl border border-slate-800 text-slate-400 text-sm">
            No advisory bulletins matching selected filter criteria.
          </div>
        ) : (
          filteredAlerts.map((alert) => {
            const isCritical = alert.severity === 'Critical';
            const isResolved = alert.status === 'Resolved';

            return (
              <div
                key={alert.id}
                className={`bg-command-900 border rounded-2xl p-5 transition-all shadow-lg hover:shadow-xl ${
                  isCritical && !isResolved
                    ? 'border-rose-500/50 shadow-rose-950/20'
                    : isResolved
                    ? 'border-slate-800/80 opacity-75'
                    : 'border-slate-800 hover:border-slate-700'
                }`}
              >
                <div className="flex flex-col lg:flex-row lg:items-start justify-between gap-4">
                  <div className="flex-1 space-y-2">
                    <div className="flex flex-wrap items-center gap-2.5">
                      <RiskBadge level={alert.severity} size="md" pulse={isCritical && !isResolved} />
                      <span className="text-xs font-mono font-bold text-cyan-400">
                        {alert.id}
                      </span>
                      <span className="text-xs text-slate-500 flex items-center gap-1">
                        <Clock size={12} /> {alert.timestamp}
                      </span>
                      <span
                        className={`text-[11px] font-bold px-2 py-0.5 rounded-full border ${
                          alert.status === 'Active'
                            ? 'bg-rose-500/20 text-rose-400 border-rose-500/40'
                            : alert.status === 'Under Review'
                            ? 'bg-amber-500/20 text-amber-400 border-amber-500/40'
                            : 'bg-emerald-500/20 text-emerald-400 border-emerald-500/40'
                        }`}
                      >
                        Status: {alert.status}
                      </span>
                    </div>

                    <h3 className="text-base sm:text-lg font-bold text-white tracking-wide">
                      {alert.title}
                    </h3>

                    <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
                      {alert.description}
                    </p>

                    {/* Metadata Pill bar */}
                    <div className="flex flex-wrap items-center gap-3 pt-2 text-xs font-mono">
                      <div className="px-2.5 py-1 rounded-lg bg-command-950 border border-slate-800 text-slate-300">
                        <span className="text-slate-500">Location:</span> {alert.location}
                      </div>
                      <div className="px-2.5 py-1 rounded-lg bg-command-950 border border-slate-800 text-slate-300">
                        <span className="text-slate-500">Zone Radius:</span> {alert.impact_radius}
                      </div>
                      <div className="px-2.5 py-1 rounded-lg bg-command-950 border border-slate-800 text-rose-400 font-bold">
                        <span className="text-slate-500">Pop. Exposed:</span> {alert.affected_pop.toLocaleString()}
                      </div>
                    </div>

                    {/* Emergency Protocol Recommendation Box */}
                    <div className="mt-3 p-3 rounded-xl bg-command-950 border border-slate-800/80 text-xs">
                      <span className="font-bold text-amber-400 flex items-center gap-1.5 mb-1">
                        <ShieldAlert size={14} /> Recommended Emergency Protocol:
                      </span>
                      <span className="text-slate-300 leading-relaxed">{alert.recommendations}</span>
                    </div>
                  </div>

                  {/* Actions Column */}
                  <div className="flex flex-row lg:flex-col gap-2 shrink-0 self-end lg:self-start w-full lg:w-48 pt-2 lg:pt-0">
                    <button
                      onClick={() => handleBroadcast(alert)}
                      className="flex-1 py-2 px-3 rounded-xl bg-rose-600 hover:bg-rose-500 text-white text-xs font-bold flex items-center justify-center gap-1.5 transition-colors shadow-md shadow-rose-950/40"
                    >
                      <Volume2 size={14} />
                      <span>Broadcast SMS</span>
                    </button>

                    <button
                      onClick={() => acknowledgeAlert(alert.id)}
                      className="flex-1 py-2 px-3 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold flex items-center justify-center gap-1.5 transition-colors border border-slate-700"
                    >
                      <CheckCircle2 size={14} className="text-emerald-400" />
                      <span>{alert.status === 'Active' ? 'Mark In Review' : 'Mark Resolved'}</span>
                    </button>

                    <button
                      onClick={() => handleInspectLocation(alert.sector_id)}
                      className="flex-1 py-2 px-3 rounded-xl bg-command-950 hover:bg-command-800 text-cyan-400 text-xs font-semibold flex items-center justify-center gap-1.5 transition-colors border border-slate-800"
                    >
                      <ExternalLink size={13} />
                      <span>Locate on Map</span>
                    </button>
                  </div>
                </div>
              </div>
            );
          })
        )}
      </div>
    </div>
  );
}
